***Creado por Jose Miguel -Valencia (España) <josemisu@yahoo.com.ar>***
***Corregido por Vicente Guerra <vic@guerra.com.mx>***

#include "minigui.ch"

Function main()

   DEFINE WINDOW WinCuePgc1 ;
      AT 50,0     ;
      WIDTH 800  ;
      HEIGHT 600 ;
      TITLE "Plan General Contable" ;
      MAIN NOMAXIMIZE ;
      NOSIZE ;
		ON INIT CuePgc_Altas()


		DEFINE TREE Tree1 AT 10,10 WIDTH 770 HEIGHT 550 VALUE 0 ITEMIDS
      END TREE

   END WINDOW
   ACTIVATE WINDOW WinCuePgc1


STATIC FUNCTION CuePgc_Altas()
LOCAL N1, cLlave, cPadre, cTexto

	WinCuePgc1.Tree1.DeleteAllItems

	aPGC := PlanGenCont()
	ASORT( aPGC,,, { |x, y| x[1] < y[1] } )

	FOR N1 := 1 TO LEN(aPGC)
		DO EVENTS
		cLlave := ALLTRIM( aPGC[ N1 ][ 1 ] )
		cPadre := LEFT( cLlave, LEN( cLlave ) - 1 )
		cTexto := cLlave + " " + aPGC[ N1 ][ 2 ]
		WinCuePgc1.Tree1.AddItem( cTexto, cPadre, cLlave )
	NEXT



FUNCTION PlanGenCont()

aPGC:={;
{'1   ','FINANCIACION BASICA','FINANCIACION BASICA'},;
{'10  ','CAPITAL','CAPITAL'},;
{'100 ','Capital social','Capital social'},;
{'1000','Capital ordinario','Capital ordinario'},;
{'1001','Capital privilegiado','Capital privilegiado'},;
{'1002','Capital sin derecho a voto','Capital sin derecho a voto'},;
{'1003','Capital con derechos restringidos','Capital con derechos restringidos'},;
{'101 ','Fondo social','Fondo social'},;
{'102 ','Capital','Capital'},;
{'11  ','RESERVAS','RESERVAS'},;
{'110 ','Prima de emision de acciones','Prima de emision de acciones'},;
{'111 ','Reservas de revalorización','Reservas de revalorización'},;
{'112 ','Reserva legal','Reserva legal'},;
{'113 ','Reservas especiales','Reservas especiales'},;
{'114 ','Reservas para acciones de sdad.dominante','Reservas para acciones de la sociedad dominante'},;
{'115 ','Reservas para acciones propias','Reservas para acciones propias'},;
{'116 ','Reservas estatutarias','Reservas estatutarias'},;
{'117 ','Reservas voluntarias','Reservas voluntarias'},;
{'118 ','Reserva por capital amortizado','Reserva por capital amortizado'},;
{'119 ','Diferencias por ajuste capital a euros','Diferencias por ajuste del capital a euros'},;
{'12  ','RESULTADOS PENDIENTES DE APLICACION','RESULTADOS PENDIENTES DE APLICACION'},;
{'120 ','Remanente','Remanente'},;
{'121 ','Resultados negativos de ejercicios ant.','Resultados negativos de ejercicios anteriores'},;
{'122 ','Aportacion socios para compensa.pérdidas','Aportaciones de socios para compensación de pérdidas'},;
{'129 ','Pérdidas y Ganancias','Pérdidas y Ganancias'},;
{'13  ','INGRESOS A DISTRIBUIR VARIOS EJERCICIOS','INGRESOS A DISTRIBUIR EN VARIOS EJERCICIOS'},;
{'130 ','Subvenciones oficiales de capital','Subvenciones oficiales de capital'},;
{'1300','Subvenciones del Estado','Subvenciones del Estado'},;
{'1301','Subvenciones de otras Administ.Públicas','Subvenciones de otras Administraciones Públicas'},;
{'131 ','Subvenciones de capital','Subvenciones de capital'},;
{'135 ','Ingresos por intereses diferidos','Ingresos por intereses diferidos'},;
{'136 ','Diferencias positivas moneda extranjera','Diferencias positivas en moneda extranjera'},;
{'137 ','Ingresos fiscales por diferen.permantes','Ingresos fiscales por diferencias permantes a distribuir en varios ejercicios'},;
{'138 ','Ingresos fiscales por deduc.y bonif.','Ingresos fiscales por deducciones y bonificaciones fiscales a distribuir en varios ejercicios'},;
{'14  ','PROVISIONES PARA RIESGOS Y GASTOS','PROVISIONES PARA RIESGOS Y GASTOS'},;
{'140 ','Provisión para pensiones y obliga.simil.','Provisión para pensiones y obligaciones similares'},;
{'141 ','Provisión para impuestos','Provisión para impuestos'},;
{'142 ','Provisión para responsabilidades','Provisión para responsabilidades'},;
{'143 ','Provisión para grandes reparaciones','Provisión para grandes reparaciones'},;
{'144 ','Fondo de reversión','Fondo de reversión'},;
{'15  ','EMPRESTITOS Y OTRAS EMISIONES ANALOGAS','EMPRESTITOS Y OTRAS EMISIONES ANALOGAS'},;
{'150 ','Obligaciones y bonos','Obligaciones y bonos'},;
{'1500','Obligaciones y bonos simples','Obligaciones y bonos simples'},;
{'1501','Obligaciones y bonos garantizados','Obligaciones y bonos garantizados'},;
{'1502','Obligaciones y bonos subordinados','Obligaciones y bonos subordinados'},;
{'1503','Obligaciones y bonos cupón cero','Obligaciones y bonos cupón cero'},;
{'1504','Obliga.y bonos c/opción de adq.acciones','Obligaciones y bonos con opción de adquisición de acciones'},;
{'1505','Obliga.y bonos c/participación en benef.','Obligaciones y bonos con participación en beneficios'},;
{'151 ','Obligaciones y bonos convertibles','Obligaciones y bonos convertibles'},;
{'155 ','Deudas represent.en otros valor.negocia.','Deudas representadas en otros valores negociables'},;
{'16  ','DEUDAS L/P EMPRESAS DEL GRUPO Y ASOCIADA','DEUDAS LARGO PLAZO CON EMPRESAS DEL GRUPO Y ASOCIADAS'},;
{'160 ','Deudas a l/p con empresas del grupo','Deudas a largo plazo con empresas del grupo'},;
{'1600','Préstamos a l/p de empresas del grupo','Préstamos a largo plazo de empresas del grupo'},;
{'1608','Deudas a l/p con emp.grupo efecto impos.','Deudas a l/p con empresas del grupo por efecto impositivo'},;
{'1609','Otras deudas a l/p con empresa del grupo','Otras deudas a largo plazo con empresas del grupo'},;
{'161 ','Deudas a l/p con empresas asociadas','Deudas a largo plazo con empresas asociadas'},;
{'162 ','Deudas l/p c/entidades crédito del grupo','Deudas a l/p con entidades de crédito del grupo'},;
{'163 ','Deudas l/p c/entidades crédito asociadas','Deudas a l/p con entidades de crédito asociadas'},;
{'164 ','Proveedores inmo. l/p empresas del grupo','Proveedores de inmovilizado a l/p, empresas grupo'},;
{'165 ','Proveedores inmo. l/p empresas asociadas','Proveedores de inmovilizado l/p, empresas asociadas'},;
{'17  ','DEUDAS L/P PRESTAMOS REC.Y OTROS CONCEP.','DEUDAS A LARGO PLAZO POR PRESTAMOS RECIBIDOS Y OTROS CONCEPTOS'},;
{'170 ','Deudas l/p con entidades de crédito','Deudas a largo plazo con entidades de crédito'},;
{'1700','Préstamos l/p de entidades de crédito','Préstamos a largo plazo de entidades de crédito'},;
{'1709','Otras deudas l/p c/entidades de crédito','Otras deudas a largo plazo con entidades de crédito'},;
{'171 ','Deudas a largo plazo','Deudas a largo plazo'},;
{'172 ','Deudas l/p transformables en subvencion','Deudas a largo plazo transformables en subvenciones'},;
{'173 ','Proveedores de inmovilizado largo plazo','Proveedores de inmovilizado a largo plazo'},;
{'174 ','Efectos a pagar a largo plazo','Efectos a pagar a largo plazo'},;
{'18  ','FIANZAS Y DEPOSITOS RECIBIDOS A L/P','FIANZAS Y DEPOSITOS RECIBIDOS A LARGO PLAZO'},;
{'180 ','Fianzas recibidas a largo plazo','Fianzas recibidas a largo plazo'},;
{'185 ','Depósitos recibidos a largo plazo','Depósitos recibidos a largo plazo'},;
{'19  ','SITUACIONES TRANSITORIAS DE FINANCIACION','SITUACIONES TRANSITORIAS DE FINANCIACION'},;
{'190 ','Accionistas por desembolsos no exigidos','Accionistas por desembolsos no exigidos'},;
{'191 ','Acc.desembolsos no exigidos emp.grupo','Accionistas por desembolsos no exigidos, empresas del grupo'},;
{'192 ','Acc.desembolsos no exigidos emp.adas.','Accionistas por desembolsos no exigidos, empresas asociadas'},;
{'193 ','Accionistas aporta.no dinerarias pend.','Accionistas por aportaciones no dinerarias pendientes'},;
{'194 ','Acc.aporta.no dineraria pend.emp.grupo','Accionistas por aportaciones no dinerarias pendientes, empresas del grupo'},;
{'195 ','Acc.aporta.no dineraria pend.emp.adas.','Accionistas por aportaciones no dinerarias pendientes, empresas asociadas'},;
{'196 ','Socios, parte no desembolsada','Socios, parte no desembolsada'},;
{'198 ','Acciones propias en situaciones especial','Acciones propias en situaciones especiales'},;
{'199 ','Acciones propias para reducción capital','Acciones propias para reducción de capital'},;
{'2   ','INMOVILIZADO','INMOVILIZADO'},;
{'20  ','GASTOS DE ESTABLECIMIENTO','GASTOS DE ESTABLECIMIENTO'},;
{'200 ','Gastos de constitución','Gastos de constitución'},;
{'201 ','Gastos de primer establecimiento','Gastos de primer establecimiento'},;
{'202 ','Gastos de ampliación de capital','Gastos de ampliación de capital'},;
{'21  ','INMOVILIZACIONES INMATERIALES','INMOVILIZACIONES INMATERIALES'},;
{'210 ','Gastos de investigación y desarrollo','Gastos de investigación y desarrollo'},;
{'2100','Gastos de I+D en proyectos no terminados','Gastos de I+D en proyectos no terminados'},;
{'2101','Gastos de I+D en proyectos terminados','Gastos de I+D en proyectos terminados'},;
{'211 ','Concesiones administrativas','Concesiones administrativas'},;
{'212 ','Propiedad industrial','Propiedad industrial'},;
{'213 ','Fondo de comercio','Fondo de comercio'},;
{'214 ','Derechos de traspaso','Derechos de traspaso'},;
{'215 ','Aplicaciones informáticas','Aplicaciones informáticas'},;
{'217 ','Derechos s/bienes régimen arrenda.finan.','Derechos sobre bienes en régimen de arrendamiento financiero'},;
{'219 ','Anticipos para inmoviliza.inmateriales','Anticipos para inmovilizaciones inmateriales'},;
{'22  ','INMOVILIZACIONES MATERIALES','INMOVILIZACIONES MATERIALES'},;
{'220 ','Terrenos y bienes naturales','Terrenos y bienes naturales'},;
{'221 ','Construcciones','Construcciones'},;
{'222 ','Instalaciones técnicas','Instalaciones técnicas'},;
{'223 ','Maquinaria','Maquinaria'},;
{'224 ','Utillaje','Utillaje'},;
{'225 ','Otras instalaciones','Otras instalaciones'},;
{'226 ','Mobiliario','Mobiliario'},;
{'227 ','Equipos para procesos de información','Equipos para procesos de información'},;
{'228 ','Elementos de transporte','Elementos de transporte'},;
{'229 ','Otro inmovilizado material','Otro inmovilizado material'},;
{'23  ','INMOVILIZACIONES MATERIALES EN CURSO','INMOVILIZACIONES MATERIALES EN CURSO'},;
{'230 ','Adaptación terrenos y bienes naturales','Adaptación de terrenos y de bienes naturales'},;
{'231 ','Construcciones en curso','Construcciones en curso'},;
{'232 ','Instalaciones técnicas en montaje','Instalaciones técnicas en montaje'},;
{'233 ','Maquinaria en montaje','Maquinaria en montaje'},;
{'237 ','Equipos para proceso información montaje','Equipos para procesos de información en montaje'},;
{'239 ','Anticipos para inmovilizacion material','Anticipos para inmovilizaciones materiales'},;
{'24  ','INVERSIONES FINAN.EN EMP.GRUPO Y ADAS.','INVERSIONES FINANCIERAS EN EMPRESAS DEL GRUPO Y ASOCIADAS'},;
{'240 ','Participaciones en empresas del grupo','Participaciones en empresas del grupo'},;
{'241 ','Participaciones en empresas asociadas','Participaciones en empresas asociadas'},;
{'242 ','Valores de renta fija de empresas grupo','Valores de renta fija de empresas del grupo'},;
{'243 ','Valores de renta fija de empresas adas.','Valores de renta fija de empresas asociadas'},;
{'244 ','Créditos l/p a empresas del grupo','Créditos a largo plazo a empresas del grupo'},;
{'2448','Créditos l/p c/emp.grupo efec.impositivo','Créditos a l/p con empresas del grupo por efecto impositivo'},;
{'245 ','Créditos l/p empresas asociadas','Créditos a largo plazo a empresas asociadas'},;
{'246 ','Intereses l/p inversion financ.emp.grupo','Intereses a l/p de inversiones financieras en empresas del grupo'},;
{'247 ','Intereses l/p inversion financ.emp.adas.','Intereses a l/p de inversiones financieras en empresas asociadas'},;
{'248 ','Desembolsos pend.sobre accion.emp.grupo','Desembolsos pendientes sobre acciones de empresas del grupo'},;
{'249 ','Desembolsos pend.sobre accion.emp.adas.','Desembolsos pendientes sobre acciones de empresas asociadas'},;
{'25  ','OTRAS INVERSIONES FINANCIERAS PERMANENTE','OTRAS INVERSIONES FINANCIERAS PERMANENTES'},;
{'250 ','Inversiones financieras permanen.capital','Inversiones financieras permanentes en capital'},;
{'2500','Inv.finan.perma.accion.c/cot.merca.s.org','Inversiones financieras permantes en acciones con cotización en mercado secundario organizado'},;
{'2501','Inv.finan.perma.accion.s/cot.merca.s.org','Inversiones financieras permantes en acciones sin cotización en mercado secundario organizado'},;
{'2502','Otras inversiones financieras en capital','Otras inversiones financieras en capital'},;
{'251 ','Valores de renta fija','Valores de renta fija'},;
{'2158','Participa.Fondos Inv.Act.Merca.Mone.l/p','Participación en Fondos de Inversión en Activos del Mercado Monetario a l/p'},;
{'252 ','Créditos a largo plazo','Créditos a largo plazo'},;
{'253 ','Créditos l/p por enajenación de inmo.','Créditos a l/p por enajenación de inmovilizado'},;
{'254 ','Creditos a largo plazo al personal','Creditos a largo plazo al personal'},;
{'256 ','Intereses l/p de valores de renta fija','Intereses a largo plazo de valores de renta fija'},;
{'257 ','Intereses a largo plazo de créditos','Intereses a largo plazo de créditos'},;
{'258 ','Imposiciones a largo plazo','Imposiciones a largo plazo'},;
{'259 ','Desembolsos pendientes sobre acciones','Desembolsos pendientes sobre acciones'},;
{'26  ','FIANZAS Y DEPOSITOS CONSTITUIDOS A L/P','FIANZAS Y DEPOSITOS CONSTITUIDOS A LARGO PLAZO'},;
{'260 ','Fianzas constituidas a largo plazo','Fianzas constituidas a largo plazo'},;
{'265 ','Depositos constituidos a largo plazo','Depositos constituidos a largo plazo'},;
{'27  ','GASTOS A DISTRIBUIR EN VARIOS EJERCICIOS','GASTOS A DISTRIBUIR EN VARIOS EJERCICIOS'},;
{'270 ','Gastos de formalización de deudas','Gastos de formalización de deudas'},;
{'271 ','Gastos intereses diferidos valores neg.','Gastos por intereses diferidos de valores negociables'},;
{'272 ','Gastos por intereses diferidos','Gastos por intereses diferidos'},;
{'28  ','AMORTIZACION ACUMULADA DEL INMOVILIZADO','AMORTIZACION ACUMULADA DEL INMOVILIZADO'},;
{'281 ','Amortiz.acum.del inmovilizado inmaterial','Amortización acumulada del inmovilizado inmaterial'},;
{'2810','Amortiz.acum.de gastos de I+D','Amortización acumulada de gastos de I+D'},;
{'2811','Amortiz.acum.de concesiones administrat.','Amortización acumulada de concesiones administrativas'},;
{'2812','Amortiz.acum.de propiedad industrial','Amortización acumulada de propiedad industrial'},;
{'2813','Amortiz.acum.de fondo de comercio','Amortización acumulada de fondo de comercio'},;
{'2814','Amortiz.acum.de derechos de traspaso','Amortización acumulada de derechos de traspaso'},;
{'2815','Amortiz.acum.aplicaciones informáticas','Amortización acumulada de aplicaciones informáticas'},;
{'2817','Amortiz.acum.der.s/bienes rég.arre.finan','Amortización acumulada de derechos sobre bienes en régimen de arrendamiento financiero'},;
{'282 ','Amortiz.acum.del inmovilizado material','Amortización acumulada del inmovilizado material'},;
{'2821','Amortiz.acum.de construcciones','Amortización acumulada de construcciones'},;
{'2822','Amortiz.acum.de instalaciones técnicas','Amortización acumulada de instalaciones técnicas'},;
{'2823','Amortización acumulada de maquinaria','Amortización acumulada de maquinaria'},;
{'2824','Amortización acumulada de utillaje','Amortización acumulada de utillaje'},;
{'2825','Amortiz.acum.de otras instalaciones','Amortización acumulada de otras instalaciones'},;
{'2826','Amortización acumulada de mobiliario','Amortización acumulada de mobiliario'},;
{'2827','Amortiz.acum.equipos procesos informáti.','Amortización acumulada de equipos para procesos informáticos'},;
{'2828','Amortiz.acum.de elementos de transporte','Amortización acumulada de elementos de transporte'},;
{'2829','Amortiz.acum.otro inmovilizado material','Amortización acumulada de otro inmovilizado material'},;
{'29  ','PROVISIONES DE INMOVILIZADO','PROVISIONES DE INMOVILIZADO'},;
{'291 ','Provisión por depreciación inmo.inmat.','Provisión por depreciación inmovilizado inmaterial'},;
{'292 ','Provisión por depreciación inmo.material','Provisión por depreciación inmovilizado material'},;
{'293 ','Prov.dep.valores negociab. l/p emp.grupo','Provisión por depreciación valores negociables l/p de empresas del grupo'},;
{'2930','Prov.dep.participa.capital l/p emp.grupo','Provisión por depreciación participaciones en capital l/p de empresas del grupo'},;
{'2935','Prov.dep.valor.renta fija l/p emp.grupo','Provisión por depreciación valores renta fija l/p de empresas del grupo'},;
{'294 ','Prov.dep.valor.negociables l/p emp.adas.','Provisión por depreciación valores negociables l/p de empresas asociadas'},;
{'2941','Prov.dep.participa.capital l/p emp.adas.','Provisión por depreciación participaciones en capital l/p de empresas asociadas'},;
{'2946','Prov.dep.valor.renta fija l/p emp.adas.','Provisión por depreciación valores renta fija l/p de empresas asociadas'},;
{'295 ','Prov.insolvencias creditos l/p emp.grupo','Provisión para insolvencias de creditos l/p a empresas del grupo'},;
{'296 ','Prov.insolvencias creditos l/p emp.adas.','Provisión para insolvencias de creditos l/p a empresasa asociadas'},;
{'297 ','Prov.dep.valores negociables l/p','Provisión por depreciación de valores negociables l/p'},;
{'298 ','Prov.insolvencias de créditos a l/p','Provisión para insolvencias de créditos a l/p'},;
{'3   ','EXISTENCIAS','EXISTENCIAS'},;
{'30  ','COMERCIALES','COMERCIALES'},;
{'300 ','Mercaderias A','Mercaderias A'},;
{'301 ','Mercaderias B','Mercaderias B'},;
{'31  ','MATERIAS PRIMAS','MATERIAS PRIMAS'},;
{'310 ','Materias primas A','Materias primas A'},;
{'311 ','Materias primas B','Materias primas B'},;
{'32  ','OTROS APROVISIONAMIENTOS','OTROS APROVISIONAMIENTOS'},;
{'320 ','Elementos y conjuntos incorporables','Elementos y conjuntos incorporables'},;
{'321 ','Combustibles','Combustibles'},;
{'322 ','Repuestos','Repuestos'},;
{'325 ','Materiales diversos','Materiales diversos'},;
{'326 ','Embalajes','Embalajes'},;
{'327 ','Envases','Envases'},;
{'328 ','Material de oficina','Material de oficina'},;
{'33  ','PRODUCTOS EN CURSO','PRODUCTOS EN CURSO'},;
{'330 ','Productos en curso A','Productos en curso A'},;
{'331 ','Productos en curso B','Productos en curso B'},;
{'34  ','PRODUCTOS SEMITERMINADOS','PRODUCTOS SEMITERMINADOS'},;
{'340 ','Productos semiterminados A','Productos semiterminados A'},;
{'341 ','Productos semiterminados B','Productos semiterminados B'},;
{'35  ','PRODUCTOS TERMINADOS','PRODUCTOS TERMINADOS'},;
{'350 ','Productos terminados A','Productos terminados A'},;
{'351 ','Productos terminados B','Productos terminados B'},;
{'36  ','SUBPRODUCTOS, RESIDUOS Y MAT.RECUPERADOS','SUBPRODUCTOS, RESIDUOS Y MATERIALES RECUPERADOS'},;
{'360 ','Subproductos A','Subproductos A'},;
{'361 ','Subproductos B','Subproductos B'},;
{'365 ','Residuos A','Residuos A'},;
{'366 ','Residuos B','Residuos B'},;
{'368 ','Materiales recuperados A','Materiales recuperados A'},;
{'369 ','Materiales recuperados B','Materiales recuperados B'},;
{'39  ','PROVISIONES POR DEPRECIACION EXISTENCIAS','PROVISIONES POR DEPRECIACION DE EXISTENCIAS'},;
{'390 ','Provisión depreciación mercaderías','Provisión por depreciación de mercaderías'},;
{'391 ','Provisión depreciación materias primas','Provisión por depreciación de materias primas'},;
{'392 ','Provisión depreciación otros aprovision.','Provisión por depreciación de otros aprovisionamientos'},;
{'393 ','Provisión depreciación de prod.en curso','Provisión por depreciación de productos en curso'},;
{'394 ','Provisión depreciación de prod.semiterm.','Provisión por depreciación de productos semiterminados'},;
{'395 ','Provisión depreciación de prod.terminado','Provisión por depreciación de productos terminado'},;
{'396 ','Prov.depre.subprod,residuos y mat.recup.','Provisión por depreciación de subproductos,residuos y materiales recuperados'},;
{'4   ','ACREEDORES Y DEUDORES','ACREEDORES Y DEUDORES POR OPERACIONES DE TRAFICO'},;
{'40  ','PROVEEDORES','PROVEEDORES'},;
{'400 ','Proveedores','Proveedores'},;
{'4000','Proveedores (euros)','Proveedores (euros)'},;
{'4004','Proveedores (moneda extranjera)','Proveedores (moneda extranjera)'},;
{'4009','Prov.facturas pend.recibir o formalizar','Proveedores facturas pendientes de recibir o formalizar'},;
{'401 ','Proveedores, efectos comerciales a pagar','Proveedores, efectos comerciales a pagar'},;
{'402 ','Proveedores, empresas del grupo','Proveedores, empresas del grupo'},;
{'4020','Proveedores, empresas del grupo (euros)','Proveedores, empresas del grupo (euros)'},;
{'4021','Efectos comerciales a pagar, emp.grupo','Efectos comerciales a pagar, empresas del grupo'},;
{'4024','Proveedores, emp.grupo (moneda extranj.)','Proveedores, empresas del grupo (moneda extranjera'},;
{'4026','Envases y emb.a devolver a prov.grupo','Envases y embalajes a devolver a proveedores, empresas del grupo'},;
{'4029','Prov.emp.grupo,facturas pend.recibir','Proveedores, empresas del grupo,facturas pendientes de recibir o formalizar'},;
{'403 ','Proveedores, empresas asociadas','Proveedores, empresas asociadas'},;
{'406 ','Envases y embalajes a devolver proveed.','Envases y embalajes a devolver a proveedores'},;
{'407 ','Anticipos a proveedores','Anticipos a proveedores'},;
{'41  ','ACREEDORES VARIOS','ACREEDORES VARIOS'},;
{'410 ','Acreedores por prestaciones de servicios','Acreedores por prestaciones de servicios'},;
{'4100','Acreedores prestaciones serv.(euros)','Acreedores por prestaciones de servicios (euros)'},;
{'4104','Acreedores prestaciones serv.(mda.ext.)','Acreedores por prestaciones de servicios (moneda extranjera)'},;
{'4109','Acreedores prest.serv.fras.pend.recibir','Acreedores por prestaciones de servicios,facturas pendientes de recibir o formalizar'},;
{'411 ','Acreedores, efectos comerciales a pagar','Acreedores, efectos comerciales a pagar'},;
{'419 ','Acreedores por operaciones en común','Acreedores por operaciones en común'},;
{'43  ','CLIENTES','CLIENTES'},;
{'430 ','Clientes','Clientes'},;
{'4300','Clientes (euros)','Clientes (euros)'},;
{'4304','Clientes (moneda extranjera)','Clientes (moneda extranjera)'},;
{'4309','Clientes, facturas pend.de formalizar','Clientes, facturas pendientes de formalizar'},;
{'431 ','Clientes, efectos comerciales a cobrar','Clientes, efectos comerciales a cobrar'},;
{'4310','Efectos comerciales en cartera','Efectos comerciales en cartera'},;
{'4311','Efectos comerciales descontados','Efectos comerciales descontados'},;
{'4312','Efectos comerciales en gestión de cobro','Efectos comerciales en gestión de cobro'},;
{'4315','Efectos comerciales impagados','Efectos comerciales impagados'},;
{'432 ','Clientes, empresas del grupo','Clientes, empresas del grupo'},;
{'4320','Clientes, empresas del grupo (euros)','Clientes, empresas del grupo (euros)'},;
{'4321','Efectos comerciales a cobrar emp.grupo','Efectos comerciales a cobrar, empresas del grupo'},;
{'4324','Clientes, empresas del grupo (mda.ext.)','Clientes, empresas del grupo (moneda extranjera)'},;
{'4326','Envases y emb.dev.a clientes, emp.grupo','Envases y embalajes a devolver a clientes, empresas del grupo'},;
{'4329','Clientes, emp.grupo,fras.pend.formalizar','Clientes, empresas del grupo, facturas pendientes formalizar'},;
{'433 ','Clientes, empresas asociadas','Clientes, empresas asociadas'},;
{'435 ','Clientes de dudoso cobro','Clientes de dudoso cobro'},;
{'436 ','Envases y embalajes a dev.por clientes','Envases y embalajes a devolver por clientes'},;
{'437 ','Anticipos de clientes','Anticipos de clientes'},;
{'44  ','DEUDORES VARIOS','DEUDORES VARIOS'},;
{'440 ','Deudores','Deudores'},;
{'4400','Deudores (euros)','Deudores (euros)'},;
{'4404','Deudores (moneda extranjera)','Deudores (moneda extranjera)'},;
{'4409','Deudores, facturas pend.de formalizar','Deudores, facturas pendientes de formalizar'},;
{'441 ','Deudores, efectos comerciales a cobrar','Deudores, efectos comerciales a cobrar'},;
{'4410','Deudores, efectos comerciales en cartera','Deudores, efectos comerciales en cartera'},;
{'4411','Deudores, efectos comerc.descontados','Deudores, efectos comerciales descontados'},;
{'4412','Deudores, efectos comerc.gestión cobro','Deudores, efectos comerciales en gestión de cobro'},;
{'4415','Deudores, efectos comerciales impagados','Deudores, efectos comerciales impagados'},;
{'445 ','Deudores de dudoso cobro','Deudores de dudoso cobro'},;
{'449 ','Deudores por operaciones en común','Deudores por operaciones en común'},;
{'46  ','PERSONAL','PERSONAL'},;
{'460 ','Anticipos de remuneraciones','Anticipos de remuneraciones'},;
{'465 ','Remuneraciones pendientes de pago','Remuneraciones pendientes de pago'},;
{'47  ','ADMINISTRACIONES PUBLICAS','ADMINISTRACIONES PUBLICAS'},;
{'470 ','H.P.deudor por diversos conceptos','Hacienda Pública, deudor por diversos conceptos'},;
{'4700','Hacienda Pública, deudor por IVA','Hacienda Pública, deudor por IVA'},;
{'4707','Hacienda Pública, deudor por IGIC','Hacienda Pública, deudor por IGIC'},;
{'4708','H.P.deudor por subvenciones concedidas','Hacienda Pública, deudor por subvenciones concedidas'},;
{'4709','H.P.deudor por devolución impuestos','Hacienda Pública, deudor por devolución impuestos'},;
{'471 ','Organismos Seguridad Social, deudores','Organismos de la Seguridad Social, deudores'},;
{'472 ','Hacienda Publica, IVA soportado','Hacienda Publica, IVA soportado'},;
{'4720','IVA soportado','IVA soportado'},;
{'4727','IGIC soportado','IGIC soportado'},;
{'473 ','H.P.retenciones y pagos a cuenta','Hacienda Pública, retenciones y pagos a cuenta'},;
{'4732','H.P.retenciones y pagos a cuenta','Hacienda Pública, retenciones y pagos a cuenta'},;
{'474 ','Impuesto s/beneficio ant.y comp.pérdidas','Impuesto sobre beneficios anticipado y compensación de pérdidas'},;
{'4740','Impuesto sobre beneficios anticipado','Impuesto sobre beneficios anticipado'},;
{'4741','Impuesto sobre beneficios anticipado l/p','Impuestos sobre beneficios anticipado a l/p'},;
{'4745','Crédito por pérdidas compensar ejer.','Crédito por pérdidas a compensar del ejercicio....'},;
{'4746','Crédito por pérdidas compensar ejer.l/p','Crédito por pérdidas a compensar del ejercicio..a l/p'},;
{'4748','Impuesto s/benef.ant.opera.intra-grupo','Impuesto sobre beneficios anticipado por operaciones intra-grupo'},;
{'4749','Crédito perdidas comp.declara.consolid.','Crédito por perdidas a compensar en régimen de declaración consolidada del ejercicio...'},;
{'475 ','H.P.acreedor por conceptos fiscales','Hacienda Pública, acreedor por conceptos fiscales'},;
{'4750','Hacienda Pública, acreedor por IVA','Hacienda Pública, acreedor por IVA'},;
{'4751','H.P.acreedor por retenciones practicadas','Hacienda Pública, acreedor por retenciones practicadas'},;
{'4752','H.P.acreedor por impuesto s/sociedades','Hacienda Pública, acreedor por impuesto sobre sociedades'},;
{'4757','Hacienda Pública, acreedor por IGIC','Hacienda Pública, acreedor por IGIC'},;
{'4758','H.P.acreedor por subvencion a reintegrar','Hacienda Pública, acreedor por subvenciones a reintegrar'},;
{'476 ','Organismos Seguridad Social, acreedores','Organismos de la Seguridad Social, acreedores'},;
{'477 ','Hacienda Pública, IVA repercutido','Hacienda Pública, IVA repercutido'},;
{'4770','IVA repercutido','IVA repercutido'},;
{'4777','IGIC repercutido','IGIC repercutido'},;
{'479 ','Impuesto sobre beneficios diferido','Impuesto sobre beneficios diferido'},;
{'4791','Impuesto sobre beneficios diferido a l/p','Impuesto sobre beneficios diferido a l/p'},;
{'4798','Impuesto s/benef.diferido ope.intra-grup','Impuesto sobre beneficios diferido por operaciones intra-grupo'},;
{'48  ','AJUSTES POR PERIODIFICACION','AJUSTES POR PERIODIFICACION'},;
{'480 ','Gastos anticipados','Gastos anticipados'},;
{'485 ','Ingresos anticipados','Ingresos anticipados'},;
{'49  ','PROVISIONES POR OPERACIONES DE TRAFICO','PROVISIONES POR OPERACIONES DE TRAFICO'},;
{'490 ','Provisión para insolvencias de tráfico','Provisión para insolvencias de tráfico'},;
{'493 ','Provisión insolvencias tráfico emp.grupo','Provisión para insolvencias de tráfico de empresas del grupo'},;
{'494 ','Provisión insolvencias tráfico emp.adas.','Provisión para insolvencias de tráfico de empresas asociadas'},;
{'499 ','Provisión para otras operacio.de tráfico','Provisión para otras operaciones de tráfico'},;
{'5   ','CUENTAS FINANCIERAS','CUENTAS FINANCIERAS'},;
{'50  ','EMPRESTITOS Y OTRAS EMI.ANALOGAS A C/P','EMPRESTITOS Y OTRAS EMISIONES ANALOGAS A CORTO PLAZO'},;
{'500 ','Obligaciones y bonos a corto plazo','Obligaciones y bonos a corto plazo'},;
{'501 ','Obligaciones y bonos convertibles a c/p','Obligaciones y bonos convertibles a corto plazo'},;
{'505 ','Deudas represent.otros valores neg.c/p','Deudas representadas otros valores negociables c/p'},;
{'506 ','Intereses empréstitos y otras emi.an lo.','Intereses de empréstitos y otras emisiones an logas'},;
{'509 ','Valores negociables amortizados','Valores negociables amortizados'},;
{'5090','Obligaciones y bonos amortizados','Obligaciones y bonos amortizados'},;
{'5091','Obligaciones y bonos convertibles amort.','Obligaciones y bonos convertibles amortizados'},;
{'5095','Otros valores negociables amortizados','Otros valores negociables amortizados'},;
{'51  ','DEUDAS C/P CON EMPRESAS GRUPO Y ADAS.','DEUDAS A CORTO PLAZO CON EMPRESAS DEL GRUPO Y ASOCIADAS'},;
{'510 ','Deudas a c/p con empresas del grupo','Deudas a corto plazo con empresas del grupo'},;
{'5100','Préstamos a c/p de empresas del grupo','Préstamos a corto plazo de empresas del grupo'},;
{'5108','Deudas a c/p con emp.grupo efectos imp.','Deudas a c/p con empresas del grupo por efectos impositivos'},;
{'5109','Otras deudas a c/p con empresas grupo','Otras deudas a corto plazo con empresas del grupo'},;
{'511 ','Deudas a c/p con empresas asociadas','Deudas a corto plazo con empresas asociadas'},;
{'512 ','Deudas a c/p entidades crédito del grupo','Deudas a c/p con entidades de crédito del grupo'},;
{'5120','Préstamos c/p entidad.crédito del grupo','Préstamos a c/p de entidades de crédito del grupo'},;
{'5128','Deudas efec.descont.entida.crédito grupo','Deudas por efectos descontados en entididades de crédito del grupo'},;
{'5129','Otras deudas c/p entida.crédit.del grupo','Otras deudas c/p con entidades de crédito del grupo'},;
{'513 ','Deudas c/p entida.credito asociadas','Deudas a c/p con entidades de credito asociadas'},;
{'514 ','Proveedores inmovilizado c/p emp.grupo','Proveedores de inmovilizado a c/p, empresas del grupo'},;
{'515 ','Proveedores inmovilizado c/p emp.adas.','Proveedores de inmovilizado a c/p, empresas asociadas'},;
{'516 ','Intereses c/p deudas con empresas grupo','Intereses a c/p de deudas con empresas del grupo'},;
{'517 ','Intereses c/p deudas con empresas adas.','Intereses a c/p de deudas con empresas asociadas'},;
{'52  ','DEUDAS A C/P POR PRESTAMOS RECIBIDOS','DEUDAS A CORTO PLAZO POR PRESTAMOS RECIBIDOS Y OTROS CONCEPTOS'},;
{'520 ','Deudas c/p con entidades de crédito','Deudas a corto plazo con entidades de crédito'},;
{'5200','Préstamos c/p de entidades de crédito','Préstamos a corto plazo de entidades de crédito'},;
{'5201','Deudas corto plazo por crédito dispuesto','Deudas a corto plazo por crédito dispuesto'},;
{'5208','Deudas por efectos descontados','Deudas por efectos descontados'},;
{'521 ','Deudas a corto plazo','Deudas a corto plazo'},;
{'523 ','Proveedores de inmovilizado corto plazo','Proveedores de inmovilizado a corto plazo'},;
{'524 ','Efectos a pagar a corto plazo','Efectos a pagar a corto plazo'},;
{'525 ','Dividendo activo a pagar','Dividendo activo a pagar'},;
{'526 ','Intereses c/p deudas entidades crédito','Intereses a c/p de deudas con entidades de crédito'},;
{'527 ','Intereses a corto plazo de deudas','Intereses a corto plazo de deudas'},;
{'53  ','INVERSIONES FINANCIERAS A CORTO PLAZO','INVERSIONES FINANCIERAS A CORTO PLAZO EN EMPRESAS DEL GRUPO Y ASOCIADAS'},;
{'530 ','Participaciones c/p en empresas grupo','Participaciones a c/p en empresas del grupo'},;
{'531 ','Participaciones c/p en empresas adas.','Participaciones a c/p en empresas asociadas'},;
{'532 ','Valores de renta fija c/p emp.grupo','Valores de renta fija a c/p de empresas del grupo'},;
{'533 ','Valores de renta fija c/p emp.asociadas','Valores de renta fija a c/p de empresas asociadas'},;
{'534 ','Créditos c/p a empresas del grupo','Créditos a corto plazo a empresas del grupo'},;
{'5348','Créditos c/p emp.grupo efecto impositivo','Créditos a c/p con empresas del grupo por efecto impositivo'},;
{'535 ','Créditos c/p a empresas asociadas','Créditos a corto plazo a empresas asociadas'},;
{'536 ','Intereses c/p inv.financieras emp.grupo','Intereses a c/p de inversiones financieras en empresas del grupo'},;
{'5360','Intereses c/p valor.renta fija emp.grupo','Intereses c/p valores renta fija de empresas del grupo'},;
{'5361','Intereses c/p de créditos a emp.grupo','Intereses c/p de créditos a empresas del grupo'},;
{'537 ','Intereses c/p inv.financieras emp.adas.','Intereses a c/p de inversiones financieras en empresas asociadas'},;
{'538 ','Desembolso pend.s/acciones c/p emp.grupo','Desembolsos pendientes sobre acciones a c/p de empresas del grupo'},;
{'539 ','Desembolso pend.s/acciones c/p emp.adas.','Desembolsos pendientes sobre acciones a c/p de empresas asociadas'},;
{'54  ','OTRAS INVERSIONES FINANCIERAS TEMPORALES','OTRAS INVERSIONES FINANCIERAS TEMPORALES'},;
{'540 ','Inversiones financieras temp.en capital','Inversiones financieras temporales en capital'},;
{'5400','Inv.finan.temp.acc.c/coti.merca.sec.org.','Inversiones financieras temporales en acciones con cotización en mercado secundario organizado'},;
{'5401','Inv.finan.temp.acc.s/coti.merca.sec.org.','Inversiones financieras temporales en acciones sin cotización en mercado secundario organizado'},;
{'5409','Otras inversiones finan.temp.en capital','Otras inversiones financieras temporales en capital'},;
{'541 ','Valores de renta fija a corto plazo','Valores de renta fija a corto plazo'},;
{'5418','Participa.Fondos Inv.Act.Merca.Monet.c/p','Participaciones en Fondos de Inversión en Activos del Mercado Monetario a c/p'},;
{'542 ','Créditos a corto plazo','Créditos a corto plazo'},;
{'543 ','Creditos c/p por enajenación de inmov.','Creditos a c/p por enajenación de inmovilizado'},;
{'544 ','Créditos a corto plazo al personal','Créditos a corto plazo al personal'},;
{'545 ','Dividendo a cobrar','Dividendo a cobrar'},;
{'546 ','Intereses c/p de valores de renta fija','Intereses a corto plazo de valores de renta fija'},;
{'547 ','Intereses a corto plazo de créditos','Intereses a corto plazo de créditos'},;
{'548 ','Imposiciones a corto plazo','Imposiciones a corto plazo'},;
{'549 ','Desembolsos pend.sobre acciones c/p','Desembolsos pendientes sobre acciones a corto plazo'},;
{'55  ','OTRAS CUENTAS NO BANCARIAS','OTRAS CUENTAS NO BANCARIAS'},;
{'550 ','Titular de la explotación','Titular de la explotación'},;
{'551 ','Cuenta corriente con empresas del grupo','Cuenta corriente con empresas del grupo'},;
{'552 ','Cuenta corriente con empresas asociadas','Cuenta corriente con empresas asociadas'},;
{'553 ','Cuenta corriente con socios y administ.','Cuenta corriente con socios y administradores'},;
{'555 ','Partidas pendientes de aplicación','Partidas pendientes de aplicación'},;
{'556 ','Desembolsos exigidos sobre acciones','Desembolsos exigidos sobre acciones'},;
{'5560','Desembolsos exigidos s/accion.emp.grupo','Desembolsos exigidos sobre acciones de empresas del grupo'},;
{'5561','Desembolsos exigidos s/accion.emp.adas.','Desembolsos exigidos sobre acciones de empresas asociadas'},;
{'5562','Desembolsos exigidos s/accion.otras emp.','Desembolsos exigidos sobre acciones de otras empresas'},;
{'557 ','Dividendo activo a cuenta','Dividendo activo a cuenta'},;
{'558 ','Accionistas por desembolsos exigidos','Accionistas por desembolsos exigidos'},;
{'56  ','FIANZAS Y DEPOSITOS RECIBID.Y CONST.C/P','FIANZAS Y DEPOSITOS RECIBIDOS Y CONSTITUIDOS A CORTO PLAZO'},;
{'560 ','Fianzas recibidas a corto plazo','Fianzas recibidas a corto plazo'},;
{'561 ','Depósitos recibidos a corto plazo','Depósitos recibidos a corto plazo'},;
{'565 ','Fianzas constituidas a corto plazo','Fianzas constituidas a corto plazo'},;
{'566 ','Depósitos constituidos a corto plazo','Depósitos constituidos a corto plazo'},;
{'57  ','TESORERIA','TESORERIA'},;
{'570 ','Caja, euros','Caja, euros'},;
{'571 ','Caja, moneda extranjera','Caja, moneda extranjera'},;
{'572 ','Bancos e inst.crédito c/c. vista, euros','Bancos e instituciones de crédito c/c. vista, euros'},;
{'573 ','Bancos e inst.crédito c/c.vista,mda.ext.','Bancos e instituciones de crédito c/c. vista, moneda extranjera'},;
{'574 ','Bancos e inst.crédito,ctas.ahorro, euros','Bancos e instituciones de crédito, cuentas de ahorro, euros'},;
{'575 ','Bancos e inst.créd.ctas.ahorro,mda.ext.','Bancos e instituciones de crédito, cuentas de ahorro, moneda extranjera'},;
{'58  ','AJUSTES POR PERIODIFICACION','AJUSTES POR PERIODIFICACION'},;
{'580 ','Intereses pagados por anticipado','Intereses pagados por anticipado'},;
{'585 ','Intereses cobrados por anticipado','Intereses cobrados por anticipado'},;
{'59  ','PROVISIONES FINANCIERAS','PROVISIONES FINANCIERAS'},;
{'593 ','Provisión depre.valor.neg.c/p emp.grupo','Provisión por depreciación de valores negociables a c/p de empresas del grupo'},;
{'594 ','Provisión depre.valor.neg.c/p emp.adas.','Provisión por depreciación de valores negociables a c/p de empresas asociadas'},;
{'595 ','Provisión insolv.créditos c/p emp.grupo','Provisión para insolvencias de créditos a c/p a empresas del grupo'},;
{'596 ','Provisión insolv.créditos c/p emp.adas.','Provisión para insolvencias de créditos a c/p a empresas asociadas'},;
{'597 ','Provisión depreciación valores nego.c/p','Provisión por depreciación de valores negociables a c/p'},;
{'598 ','Provisión para insolvencias créditos c/p','Provisión para insolvencias de créditos a c/p'},;
{'6   ','COMPRAS Y GASTOS','COMPRAS Y GASTOS'},;
{'60  ','COMPRAS','COMPRAS'},;
{'600 ','Compras de mercaderías','Compras de mercaderías'},;
{'601 ','Compras de materias primas','Compras de materias primas'},;
{'602 ','Compras de otros aprovisionamientos','Compras de otros aprovisionamientos'},;
{'607 ','Trabajos realizados por otras empresas','Trabajos realizados por otras empresas'},;
{'608 ','Devoluciones compras y opera.similares','Devoluciones de compras y operaciones similares'},;
{'6080','Devoluciones de compras de mercaderías','Devoluciones de compras de mercaderías'},;
{'6081','Devoluciones de compras materias primas','Devoluciones de compras de materias primas'},;
{'6082','Devoluciones compras otros aprovisiona.','Devoluciones de compras de otros aprovisionamientos'},;
{'609 ','"Rappels" por compras','"Rappels" por compras'},;
{'6090','"Rappels" por compras de mercaderías','"Rappels" por compras de mercaderías'},;
{'6091','"Rappels" por compras de materias primas','"Rappels" por compras de materias primas'},;
{'6092','"Rappels" por compras otros aprovisiona.','"Rappels" por compras de otros aprovisionamientos'},;
{'61  ','VARIACION DE EXISTENCIAS','VARIACION DE EXISTENCIAS'},;
{'610 ','Variación de existencias de mercaderías','Variación de existencias de mercaderías'},;
{'611 ','Variación de existencias materias primas','Variación de existencias de materias primas'},;
{'612 ','Variación existencias otros aprovisiona.','Variación de existencias de otros aprovisionamientos'},;
{'62  ','SERVICIOS EXTERIORES','SERVICIOS EXTERIORES'},;
{'620 ','Gastos investiga.y desarrollo ejercicio','Gastos en investigación y desarrollo del ejercicio'},;
{'621 ','Arrendamientos y cánones','Arrendamientos y cánones'},;
{'622 ','Reparaciones y conservación','Reparaciones y conservación'},;
{'623 ','Servicios de profesionales independiente','Servicios de profesionales independientes'},;
{'624 ','Transportes','Transportes'},;
{'625 ','Primas de seguros','Primas de seguros'},;
{'626 ','Servicios bancarios y similares','Servicios bancarios y similares'},;
{'627 ','Publicidad,propaganda y relacio.públicas','Publicidad, propaganda y relaciones públicas'},;
{'628 ','Suministros','Suministros'},;
{'629 ','Otros servicios','Otros servicios'},;
{'63  ','TRIBUTOS','TRIBUTOS'},;
{'630 ','Impuesto sobre beneficios','Impuesto sobre beneficios'},;
{'631 ','Otros tributos','Otros tributos'},;
{'632 ','Sociedades transp.efecto impositivo','Sociedades transparentes, efecto impositivo'},;
{'6320','Importes a cuenta no recup.entid.transp.','Importes a cuenta no recuperables por entidades transparentes'},;
{'6321','Importes a cuenta no recup.agrup.int.eco','Importes a cuenta no recuperables por agrupaciones de interés económico'},;
{'6323','Ajustes negativos en imposi.soci.transp.','Ajustes negativos en la imposición en sociedades transparentes'},;
{'6328','Ajustes positivos en imposi.soci.transp.','Ajustes positivos en la imposición en sociedades transparentes'},;
{'633 ','Ajustes negativos en imposi.sobre benef.','Ajustes negativos en imposicion sobre beneficios'},;
{'634 ','Ajustes negativos en imposi.indirecta','Ajustes negativos en la imposicion indirecta'},;
{'6341','Ajustes negativos en IVA de circulante','Ajustes negativos en IVA de circulante'},;
{'6342','Ajustes negativos en IVA de inversiones','Ajustes negativos en IVA de inversiones'},;
{'6343','Ajustes negativos en IGIC, de circulante','Ajustes negativos en IGIC, de circulante'},;
{'6344','Ajustes negativos en IGIC, de inversión','Ajustes negativos en IGIC, de inversión'},;
{'635 ','Impuesto sobre beneficios extranjero','Impuesto sobre beneficios extranjero'},;
{'636 ','Devolución de impuestos','Devolución de impuestos'},;
{'637 ','Imposición indirecta,regímenes especial.','Imposición indirecta, regímenes especiales'},;
{'6371','Régimen simplificado, IVA','Régimen simplificado, IVA'},;
{'6372','Régimen simplificado, IGIC','Régimen simplificado, IGIC'},;
{'6373','Régimen agricultura,ganad.y pesca, IVA','Régimen de la agricultura,ganadería y pesca, IVA'},;
{'6374','Régimen agricultura y ganadería, IGIC','Régimen de la agricultura y ganadería, IGIC'},;
{'638 ','Ajustes positivos en imposicion s/benef.','Ajustes positivos en imposicion sobre beneficios'},;
{'639 ','Ajustes positivos en imposicion indirec.','Ajustes positivos en la imposicion indirecta'},;
{'6391','Ajustes positivos en IVA de circulante','Ajustes positivos en IVA de circulante'},;
{'6392','Ajustes positivos en IVA de inversiones','Ajustes positivos en IVA de inversiones'},;
{'6393','Ajustes positivos en IGIC de circulante','Ajustes positivos en IGIC de circulante'},;
{'6394','Ajustes positivos en IGIC de inversión','Ajustes positivos en IGIC de inversión'},;
{'64  ','GASTOS DE PERSONAL','GASTOS DE PERSONAL'},;
{'640 ','Sueldos y salarios','Sueldos y salarios'},;
{'641 ','Indemnizaciones','Indemnizaciones'},;
{'642 ','Seguridad Social a cargo de la empresa','Seguridad Social a cargo de la empresa'},;
{'643 ','Aportaciones a sistemas comp.pensiones','Aportaciones a sistemas complementarios pensiones'},;
{'649 ','Otros gastos sociales','Otros gastos sociales'},;
{'65  ','OTROS GASTOS DE GESTION','OTROS GASTOS DE GESTION'},;
{'650 ','Pérdidas créditos comerciales incobrab.','Pérdidas de créditos comerciales incobrables'},;
{'651 ','Resultados de operaciones en común','Resultados de operaciones en común'},;
{'6510','Beneficio transferido (gestor)','Beneficio transferido (gestor)'},;
{'6511','Pérdida sop.(partícipe o aso.no gestor)','Pérdida soportada (partícipe o asociado no gestor)'},;
{'659 ','Otras pérdidas en gestión corriente','Otras pérdidas en gestión corriente'},;
{'66  ','GASTOS FINANCIEROS','GASTOS FINANCIEROS'},;
{'661 ','Intereses de obligaciones y bonos','Intereses de obligaciones y bonos'},;
{'6610','Intereses obliga.y bonos l/p emp.grupo','Intereses de obligaciones y bonos l/p en empresas del grupo'},;
{'6611','Intereses obliga.y bonos l/p emp.adas.','Intereses de obligaciones y bonos l/p en empresas asociadas'},;
{'6613','Intereses obliga.y bonos l/p otras emp.','Intereses de obligaciones y bonos l/p en otras empresas'},;
{'6615','Intereses obliga.y bonos c/p emp.grupo','Intereses de obligaciones y bonos c/p en empresas del grupo'},;
{'6616','Intereses obliga.y bonos c/p emp.adas.','Intereses de obligaciones y bonos c/p en empresas asociadas'},;
{'6618','Intereses obliga.y bonos c/p otras emp.','Intereses de obligaciones y bonos c/p en otras empresas'},;
{'662 ','Intereses de deudas a largo plazo','Intereses de deudas a largo plazo'},;
{'6620','Intereses de deudas a l/p con emp.grupo','Intereses de deudas a l/p con empresas del grupo'},;
{'6621','Intereses de deudas a l/p con emp.adas.','Intereses de deudas a l/p con empresas asociadas'},;
{'6622','Intereses de deudas l/p con ent.crédito','Intereses de deudas a l/p con entidades de crédito'},;
{'6623','Intereses de deudas a l/p con otras emp.','Intereses de deudas a l/p con otras empresas'},;
{'663 ','Intereses de deudas a corto plazo','Intereses de deudas a corto plazo'},;
{'6630','Intereses de deudas a c/p con emp.grupo','Intereses de deudas a c/p con empresas del grupo'},;
{'6631','Intereses de deudas a c/p con emp.adas.','Intereses de deudas a c/p con empresas asociadas'},;
{'6632','Intereses de deudas c/p con ent.crédito','Intereses de deudas a c/p con entidades de crédito'},;
{'6633','Intereses de deudas a c/p con otras emp.','Intereses de deudas a c/p con otras empresas'},;
{'664 ','Intereses por descuento de efectos','Intereses por descuento de efectos'},;
{'6640','Intereses desc.efectos ent.crédito grupo','Intereses por descuento de efectos en entidades de crédito del grupo'},;
{'6641','Intereses desc.efectos ent.crédito adas.','Intereses por descuento de efectos en entidades de crédito asociadas'},;
{'6643','Intereses desc.efectos otras ent.crédito','Intereses por descuento de efectos en otras entidades de crédito'},;
{'665 ','Descuentos sobre ventas por pronto pago','Descuentos sobre ventas por pronto pago'},;
{'6650','Desc.s/ventas pronto pago a emp.grupo','Descuentos sobre ventas por pronto pago a empresas del grupo'},;
{'6651','Desc.s/ventas pronto pago a emp.adas.','Descuentos sobre ventas por pronto pago a empresas asociadas'},;
{'6653','Desc.s/ventas pronto pago a otras emp.','Descuentos sobre ventas por pronto pago a otras empresas'},;
{'666 ','Pérdidas en valores negociables','Pérdidas en valores negociables'},;
{'6660','Pérdidas valores negocia.l/p emp.grupo','Pérdidas en valores negociables a l/p de empresas del grupo'},;
{'6661','Pérdidas valores negocia.l/p emp.adas.','Pérdidas en valores negociables a l/p de empresas asociadas'},;
{'6663','Pérdidas valores negocia.l/p otras emp.','Pérdidas en valores negociables a l/p de otras empresas'},;
{'6665','Pérdidas valores negocia.c/p emp.grupo','Pérdidas en valores negociables a c/p de empresas del grupo'},;
{'6666','Pérdidas valores negocia.c/p emp.adas.','Pérdidas en valores negociables a c/p de empresas asociadas'},;
{'6668','Pérdidas valores negocia.c/p otras emp.','Pérdidas en valores negociables a c/p de otras empresas'},;
{'667 ','Pérdidas de créditos','Pérdidas de créditos'},;
{'6670','Pérdidas de créditos a l/p a emp.grupo','Pérdidas de créditos a l/p a empresas del grupo'},;
{'6671','Pérdidas de créditos a l/p a emp.adas.','Pérdidas de créditos a l/p a empresas asociadas'},;
{'6673','Pérdidas de créditos a l/p a otras emp.','Pérdidas de créditos a l/p a otras empresas'},;
{'6675','Pérdidas de créditos a c/p a emp.grupo','Pérdidas de créditos a c/p a empresas del grupo'},;
{'6676','Pérdidas de créditos a c/p a emp.adas.','Pérdidas de créditos a c/p a empresas asociadas'},;
{'6678','Pérdidas de créditos a c/p a otras emp.','Pérdidas de créditos a c/p a otras empresas'},;
{'668 ','Diferencias negativas de cambio','Diferencias negativas de cambio'},;
{'6680','Diferencias neg.cambio introduc.del euro','Diferencias negativas de cambio por la introducción del euro'},;
{'6681','Diferencias negativas de cambio','Diferencias negativas de cambio'},;
{'669 ','Otros gastos financieros','Otros gastos financieros'},;
{'6690','Gastos por dif.derivad.redondeo del euro','Gastos por diferencias derivadas del redondeo del euro'},;
{'6691','Otros gastos financieros','Otros gastos financieros'},;
{'67  ','PERDIDAS PROCEDENTES INMOV.Y GTOS.EXCEP.','PERDIDAS PROCEDENTES DEL INMOVILIZADO Y GASTOS EXCEPCIONALES'},;
{'670 ','Pérdidas procedentes inmov.inmaterial','Pérdidas procedentes de inmovilizado inmaterial'},;
{'671 ','Pérdidas procedentes inmov.material','Pérdidas procedentes de inmovilizado material'},;
{'672 ','Pérdidas proc.part.capital l/p emp.grupo','Pérdidas procedentes de participaciones en capital a l/p de empresas del grupo'},;
{'673 ','Pérdidas proc.part.capital l/p emp.adas.','Pérdidas procedentes de participaciones en capital a l/p de empresas asociadas'},;
{'674 ','Pérdidas opera.c/acciones y obliga.prop.','Pérdidas por operaciones con acciones y obligaciones propias'},;
{'676 ','Donaciones del inmovilizado material','Donaciones del inmovilizado material'},;
{'678 ','Gastos extraordinarios','Gastos extraordinarios'},;
{'6780','Gastos producidos por introduc.del euro','Gastos producidos por la introducción del euro'},;
{'6781','Otros gastos extraordinarios','Otros gastos extraordinarios'},;
{'679 ','Gastos y pérdidas ejercicios anteriores','Gastos y pérdidas de ejercicios anteriores'},;
{'68  ','DOTACIONES PARA AMORTIZACIONES','DOTACIONES PARA AMORTIZACIONES'},;
{'680 ','Amortización gastos de establecimiento','Amortización de gastos de establecimiento'},;
{'681 ','Amortización del inmovilizado inmaterial','Amortización del inmovilizado inmaterial'},;
{'682 ','Amortización del inmovilizado material','Amortización del inmovilizado material'},;
{'69  ','DOTACIONES A LAS PROVISIONES','DOTACIONES A LAS PROVISIONES'},;
{'690 ','Dotación al fondo de reversión','Dotación al fondo de reversión'},;
{'691 ','Dotación provisión inmov.inmaterial','Dotación a la provisión de inmovilizado inmaterial'},;
{'692 ','Dotación provisión inmov.material','Dotación a la provisión del inmovilizado material'},;
{'693 ','Dotación provisión existencias','Dotación a la provisión de existencias'},;
{'694 ','Dotación provisión insolvencias tráfico','Dotación a la provisión para insolvencias de tráfico'},;
{'695 ','Dotación provisión otras oper.de tráfico','Dotación a la provisión para otras operaciones de tráfico'},;
{'696 ','Dotación provisión valores negocia.l/p','Dotación a la provisión para valores negociables a l/p'},;
{'6960','Dotación prov.part.capital l/p emp.grupo','Dotación a la provisión para participaciones en capital a l/p de empresas del grupo'},;
{'6961','Dotación prov.part.capital l/p emp.adas.','Dotación a la provisión para participaciones en capital a l/p de empresas asociadas'},;
{'6963','Dotación prov.part.capital l/p otras emp','Dotación a la provisión para participaciones en capital a l/p de otras empresas'},;
{'6965','Dotación prov.valor.rent.fija l/p emp.gr','Dotación a la provisión para valores de renta fija a l/p de empresas del grupo'},;
{'6966','Dotación prov.valor.rent.fija l/p emp.as','Dotación a la provisión para valores de renta fija a l/p de empresas asociadas'},;
{'697 ','Dotación provisión insolv.créditos l/p','Dotación a la provisión para insolvencias de créditos a l/p'},;
{'6970','Dotación prov.insolv.crédit.l/p emp.gr.','Dotación a la provisión para insolvencias de créditos a l/p a empresas del grupo'},;
{'6971','Dotación prov.insolv.crédit.l/p emp.adas','Dotación a la provisión para insolvencias de créditos a l/p a empresas asociadas'},;
{'6973','Dotación prov.insolv.crédit.l/p otra.emp','Dotación a la provisión para insolvencias de créditos a l/p a otras empresas'},;
{'698 ','Dotacion provisión valores negocia.c/p','Dotacion a la provisión para valores negociables a c/p'},;
{'6980','Dotacion prov.valores negocia.c/p emp.gr','Dotacion a la provisión para valores negociables a c/p de empresas del grupo'},;
{'6981','Dotacion prov.valores negocia.c/p emp.as','Dotacion a la provisión para valores negociables a c/p de empresas asociadas'},;
{'6983','Dotacion prov.valores nego.c/p otras emp','Dotacion a la provisión para valores negociables a c/p de otras empresas'},;
{'699 ','Dotación provisión insolv.créditos c/p','Dotación a la provisión para insolvencias de créditos a c/p'},;
{'6990','Dotación prov.insolv.créditos c/p emp.gr','Dotación a la provisión para insolvencias de créditos a c/p a empresas del grupo'},;
{'6991','Dotación prov.insolv.créditos c/p emp.as','Dotación a la provisión para insolvencias de créditos a c/p a empresas asociadas'},;
{'6993','Dotación prov.insolv.créd.c/p otras emp.','Dotación a la provisión para insolvencias de créditos a c/p a otras empresas'},;
{'7   ','VENTAS E INGRESOS','VENTAS E INGRESOS'},;
{'70  ','VENTAS DE MERCADERIAS, SERVICIOS, ETC.','VENTAS DE MERCADERIAS,DE PRODUCCION PROPIA,DE SERVICIOS, ETC.'},;
{'700 ','Ventas de mercaderías','Ventas de mercaderías'},;
{'701 ','Ventas de productos terminados','Ventas de productos terminados'},;
{'702 ','Ventas de productos semiterminados','Ventas de productos semiterminados'},;
{'703 ','Ventas de subproductos y residuos','Ventas de subproductos y residuos'},;
{'704 ','Ventas de envases y embalajes','Ventas de envases y embalajes'},;
{'705 ','Prestaciones de servicios','Prestaciones de servicios'},;
{'708 ','Devoluciones de ventas y opera.similares','Devoluciones de ventas y operaciones similares'},;
{'7080','Devoluciones de ventas de mercaderías','Devoluciones de ventas de mercaderías'},;
{'7081','Devoluciones de ventas prod.terminados','Devoluciones de ventas de productos terminados'},;
{'7082','Devoluciones de ventas prod.semitermi','Devoluciones de ventas de productos semiterminados'},;
{'7083','Devoluciones ventas subprod.y residuos','Devoluciones de ventas de subproductos y residuos'},;
{'7084','Devoluciones de ventas de envases y emb.','Devoluciones de ventas de envases y embalajes'},;
{'709 ','"Rappels" sobre ventas','"Rappels" sobre ventas'},;
{'7090','"Rappels" sobre ventas de mercaderías','"Rappels" sobre ventas de mercaderías'},;
{'7091','"Rappels" sobre ventas prod.terminados','"Rappels" sobre ventas de productos terminados'},;
{'7092','"Rappels" sobre ventas prod.semitermina.','"Rappels" sobre ventas de productos semiterminados'},;
{'7093','"Rappels" sobre ventas subpro.y residuos','"Rappels" sobre ventas de subproductos y residuos'},;
{'7094','"Rappels" sobre ventas envases y emb.','"Rappels" sobre ventas de envases y embalajes'},;
{'71  ','VARIACION DE EXISTENCIAS','VARIACION DE EXISTENCIAS'},;
{'710 ','Variación de existencias prod.en curso','Variación de existencias de productos en curso'},;
{'711 ','Variación existencias prod.semitermina.','Variación de existencias de productos semiterminados'},;
{'712 ','Variación existencias prod.terminados','Variación de existencias de productos terminados'},;
{'713 ','Variación existencias subprod.residuos','Variación de existencias de subproductos, residuos y materiales recuperados'},;
{'73  ','TRABAJOS REALIZADOS PARA LA EMPRESA','TRABAJOS REALIZADOS PARA LA EMPRESA'},;
{'730 ','Incorporación al activo gtos.establecim.','Incorporación al activo de gastos de establecimiento'},;
{'731 ','Trabajos realizados inmov.inmaterial','Trabajos realizados para inmovilizado inmaterial'},;
{'732 ','Trabajos realizados inmov.material','Trabajos realizados para inmovilizado material'},;
{'733 ','Trabajos realizados inmov.material curso','Trabajos realizados para inmovilizado material en curso'},;
{'737 ','Incorpora.al activo gtos.formaliz.deudas','Incorporación al activo de gastos de formalización de deudas'},;
{'74  ','SUBVENCIONES A LA EXPLOTACION','SUBVENCIONES A LA EXPLOTACION'},;
{'740 ','Subvenciones oficiales a la explotación','Subvenciones oficiales a la explotación'},;
{'741 ','Otras subvenciones a la explotación','Otras subvenciones a la explotación'},;
{'75  ','OTROS INGRESOS DE GESTION','OTROS INGRESOS DE GESTION'},;
{'751 ','Resultados de operaciones en común','Resultados de operaciones en común'},;
{'7510','Pérdida transferida (gestor)','Pérdida transferida (gestor)'},;
{'7511','Beneficio atribuido (partícipe)','Beneficio atribuido (partícipe o asociado no gestor)'},;
{'752 ','Ingresos por arrendamientos','Ingresos por arrendamientos'},;
{'753 ','Ingresos propiedad indus.cedida explota.','Ingresos de propiedad industrial cedida en explotación'},;
{'754 ','Ingresos por comisiones','Ingresos por comisiones'},;
{'755 ','Ingresos por servicios al personal','Ingresos por servicios al personal'},;
{'759 ','Ingresos por servicios diversos','Ingresos por servicios diversos'},;
{'76  ','INGRESOS FINANCIEROS','INGRESOS FINANCIEROS'},;
{'760 ','Ingresos de participaciones en capital','Ingresos de participaciones en capital'},;
{'7600','Ingresos de particip.capital emp.grupo','Ingresos de participaciones en capital de empresas del grupo'},;
{'7601','Ingresos de particip.capital emp.adas.','Ingresos de participaciones en capital de empresas asociadas'},;
{'7603','Ingresos de particip.capital otras emp.','Ingresos de participaciones en capital de otras empresas'},;
{'761 ','Ingresos de valores de renta fija','Ingresos de valores de renta fija'},;
{'7610','Ingresos de valores renta fija emp.grupo','Ingresos de valores renta fija de empresas del grupo'},;
{'7611','Ingresos de valores renta fija emp.adas.','Ingresos de valores renta fija de empresas asociadas'},;
{'7613','Ingresos de valores renta fija otras emp','Ingresos de valores renta fija de otras empresas'},;
{'7618','Ing.parti.Fond.Inver.Activ.Merca.Monet.','Ingresos de participaciones en Fondos de Inversión en Activos del Mercado Monetario'},;
{'762 ','Ingresos de créditos a largo plazo','Ingresos de créditos a largo plazo'},;
{'7620','Ingresos de créditos a l/p a emp.grupo','Ingresos de créditos a l/p a empresas del grupo'},;
{'7621','Ingresos de créditos a l/p a emp.adas.','Ingresos de créditos a l/p a empresas asociadas'},;
{'7623','Ingresos de créditos a l/p a otras emp.','Ingresos de créditos a l/p a otras empresas'},;
{'763 ','Ingresos de créditos a corto plazo','Ingresos de créditos a corto plazo'},;
{'7630','Ingresos de créditos a c/p a emp.grupo','Ingresos de créditos a c/p a empresas del grupo'},;
{'7631','Ingresos de créditos a c/p a emp.adas.','Ingresos de créditos a c/p a empresas asociadas'},;
{'7633','Ingresos de créditos a c/p a otras emp.','Ingresos de créditos a c/p a otras empresas'},;
{'765 ','Descuentos sobre compras por pronto pago','Descuentos sobre compras por pronto pago'},;
{'7650','Desc.s/compras pronto pago emp.grupo','Descuentos sobre compras por pronto pago de empresas del grupo'},;
{'7651','Desc.s/compras pronto pago emp.adas.','Descuentos sobre compras por pronto pago de empresas asociadas'},;
{'7653','Desc.s/compras pronto pago otras emp.','Descuentos sobre compras por pronto pago de otras empresas'},;
{'766 ','Beneficios en valores negociables','Beneficios en valores negociables'},;
{'7660','Beneficios valores negocia.l/p emp.grupo','Beneficios en valores negociables a l/p de empresas del grupo'},;
{'7661','Beneficios valores negocia.l/p emp.adas.','Beneficios en valores negociables a l/p de empresas asociadas'},;
{'7663','Beneficios valores negocia.l/p otras emp','Beneficios en valores negociables a l/p de otras empresas'},;
{'7665','Beneficios valores negocia.c/p emp.grupo','Beneficios en valores negociables a c/p de empresas del grupo'},;
{'7666','Beneficios valores negocia.c/p emp.adas.','Beneficios en valores negociables a c/p de empresas asociadas'},;
{'7668','Beneficios valores negocia.c/p otras emp','Beneficios en valores negociables a c/p de otras empresas'},;
{'768 ','Diferencias positivas de cambio','Diferencias positivas de cambio'},;
{'7680','Diferencias posi.cambio por int.del euro','Diferencias positivas de cambio por la introducción del euro'},;
{'7681','Diferencias positivas de cambio','Diferencias positivas de cambio'},;
{'769 ','Otros ingresos financieros','Otros ingresos financieros'},;
{'7690','Ingresos por diferen.redondeo del euro','Ingresos por diferencias derivadas del redondeo del euro'},;
{'7691','Otros ingresos financieros','Otros ingresos financieros'},;
{'77  ','BENEFICIOS PROCEDENTES INMOV.E ING.EXCEP','BENEFICIOS PROCEDENTES DEL INMOVILIZADO E INGRESOS EXCEPCIONALES'},;
{'770 ','Beneficios procedentes inmov.inmaterial','Beneficios procedentes de inmovilizado inmaterial'},;
{'771 ','Beneficios procedentes inmov.material','Beneficios procedentes de inmovilizado material'},;
{'772 ','Benef.proced.parti.capital l/p emp.grupo','Beneficios procedentes de participaciones en capital a l/p de empresas del grupo'},;
{'773 ','Benef.proced.parti.capital l/p emp.adas.','Beneficios procedentes de participaciones en capital a l/p de empresas asociadas'},;
{'774 ','Benef.operacio.acciones y obliga.propias','Beneficios por operaciones con acciones y obligaciones propias'},;
{'775 ','Subvenciones capital trasp.result.ejer.','Subvenciones de capital traspasadas al resultado del ejercicio'},;
{'778 ','Ingresos extraordinarios','Ingresos extraordinarios'},;
{'779 ','Ingresos y benef.ejercicios anteriores','Ingresos y beneficios de ejercicios anteriores'},;
{'79  ','EXCESOS Y APLICACIONES DE PROVISIONES','EXCESOS Y APLICACIONES DE PROVISIONES'},;
{'790 ','Exceso de provisión para riesgos y gtos.','Exceso de provisión para riesgos y gastos'},;
{'791 ','Exceso de provisión del inmov.inmaterial','Exceso de provisión del inmovilizado inmaterial'},;
{'792 ','Exceso de provisión del inmov.material','Exceso de provisión del inmovilizado material'},;
{'793 ','Provisión de existencias aplicada','Provisión de existencias aplicada'},;
{'794 ','Provisión insolvencias tráfico aplicada','Provisión para insolvencias de tráfico aplicada'},;
{'795 ','Provisión otras operaci.tráfico aplicada','Provisión para otras operaciones de tráfico aplicada'},;
{'796 ','Exceso provisión valores negociables l/p','Exceso de provisión para valores negociables a l/p'},;
{'7960','Exceso prov.partic.capital l/p emp.grupo','Exceso de provisión para participaciones en capital a l/p de empresas del grupo'},;
{'7961','Exceso prov.partic.capital l/p emp.adas.','Exceso de provisión para participaciones en capital a l/p de empresas asociadas'},;
{'7963','Exceso prov.valor.negocia.l/p otras emp.','Exceso de provisión para valores negociables a l/p de otras empresas'},;
{'7965','Exceso prov.valor.renta fija l/p emp.gr.','Exceso de provisión para valores de renta fija a l/p de empresas del grupo'},;
{'7966','Exceso prov.valor.renta fija l/p emp.as.','Exceso de provisión para valores de renta fija a l/p de empresas asociadas'},;
{'797 ','Exceso prov.insolvencias de créditos l/p','Exceso de provisión para insolvencias de créditos a l/p'},;
{'7970','Exceso prov.insolv.crédit.l/p emp.grupo','Exceso de provisión para insolvencias de créditos a l/p de empresas del grupo'},;
{'7971','Exceso prov.insolv.crédit.l/p emp.adas.','Exceso de provisión para insolvencias de créditos a l/p de empresas asociadas'},;
{'7973','Exceso prov.insolv.crédit.l/p otras emp.','Exceso de provisión para insolvencias de créditos a l/p de otras empresas'},;
{'798 ','Exceso prov.valores negociables c/p','Exceso de provisión para valores negociables a c/p'},;
{'7980','Exceso prov.valor.negocia.c/p emp.grupo','Exceso de provisión para valores negociables a c/p de empresas del grupo'},;
{'7981','Exceso prov.valor.negocia.c/p emp.adas.','Exceso de provisión para valores negociables a c/p de empresas asociadas'},;
{'7983','Exceso prov.valor.negocia.c/p otras emp.','Exceso de provisión para valores negociables a c/p de otras empresas'},;
{'799 ','Exceso prov.insolvencias de créditos c/p','Exceso de provisión para insolvencias de créditos a c/p'},;
{'7990','Exceso prov.insolv.crédit.c/p emp.grupo','Exceso de provisión para insolvencias de créditos a c/p de empresas del grupo'},;
{'7991','Exceso prov.insolv.crédit.c/p emp.adas.','Exceso de provisión para insolvencias de créditos a c/p de empresas asociadas'},;
{'7993','Exceso prov.insolv.crédit.c/p otras emp.','Exceso de provisión para insolvencias de créditos a c/p de otras empresas'}}

RETURN(aPGC)